Feat/select team pokemon
naftalima/pokebattle pull request #10
Opened 2021-06-07 12:52 UTC by naftalima

## Objective and Motivation
- The trainer selects the 3 pokemons for her/his team.

2021-06-08 17:27 UTC, rsarai requested changes

2021-06-08 17:27 UTC, rsarai commented on backend/battles/views.py
>  # HACK : should be a UpdateView
You can already remove this comment

2021-06-08 17:27 UTC, rsarai commented on backend/battles/views.py
>      # TODO : do the validation on the form
Are these comments necessary?

2021-06-08 17:27 UTC, rsarai commented on backend/battles/views.py
> +    # success_url = reverse_lazy("battle-team-pokemons")
You can remove this if is not being used

2021-06-08 17:27 UTC, rsarai commented on backend/battles/views.py
> +        # BUG can't challenged yourself
This comment can also be removed right?

2021-06-08 17:27 UTC, rsarai commented on backend/battles/views.py
> +from .forms import BattleForm, TeamForm
Let's change this to use absolute imports

2021-06-08 17:27 UTC, rsarai commented on backend/battles/templatetags/battles_tags.py
> +from ..models import Battle, Team
Let's change this to use absolute imports :pray:

2021-06-08 17:27 UTC, rsarai commented on backend/battles/templates/battles/battles.html
> +  {% comment %}
The following block of comments is required or can we remove it?

2021-06-08 17:27 UTC, rsarai commented on backend/battles/pokemon.py
> +    print(points)
:eyes:

2021-06-08 17:27 UTC, rsarai commented on backend/battles/forms.py
> +from .models import Battle, Team, TeamPokemon
Let's change this to use absolute imports :pray:

2021-06-08 18:30 UTC, naftalima commented on backend/battles/pokemon.py
> +    print(points)
IDK why but it only works that way  👁️👁️

2021-06-08 19:57 UTC, rsarai commented on backend/battles/services/logic_team_pokemon.py
> +def sum_points(pokemons):
Did you discuss this with Flavio?

2021-06-08 19:58 UTC, rsarai commented on backend/battles/services/logic_team_pokemon.py
> +def sum_points(pokemons):
I mean the name of the module

2021-06-08 20:01 UTC, naftalima commented on backend/battles/templatetags/battles_tags.py
> +# custom_tags.py
no 😅

2021-06-08 20:03 UTC, naftalima commented on backend/battles/services/logic_team_pokemon.py
> +def sum_points(pokemons):
i don't remember, but definitely can be improved

2021-06-08 20:04 UTC, naftalima commented on backend/battles/services/logic_team_pokemon.py
> +def sum_points(pokemons):
yes 🥰

2021-06-09 20:07 UTC, naftalima commented
I got confused when I solved the previous conflict 😕

2021-06-15 15:24 UTC, fjsj commented on backend/battles/templatetags/battles_tags.py
> +    team_id = Team.objects.get(battle=battle, trainer=user).id
This will generate new queries. Consider not making new queries on filter tags.

2021-06-15 15:26 UTC, fjsj approved these changes
LGTM, there are additional queries that can be optimized, but you can tackle this later.

2021-06-17 18:24 UTC, merged