Feat/battle
naftalima/pokebattle pull request #13
Opened 2021-06-09 20:03 UTC by naftalima

## Objective and Motivation
- Pokemons from Trainer1 will battle against Pokemons from Trainer2.

2021-06-09 23:23 UTC, naftalima commented
run_turns() definitely can be improved 😼

2021-06-09 23:26 UTC, naftalima commented
I noticed now that there is a problem. The pokemons are not in the correct order. I'll try to fix it tomorrow morning.

2021-06-10 13:30 UTC, fjsj reviewed
LGTM, but wait for Rebeca's final review

2021-06-15 15:45 UTC, fjsj commented on backend/battles/views.py
> +        creator_team_has_pokemons = battle.teams.all().get(trainer=battle.creator).pokemons.exists()
To avoid getting the team then checking if that team has pokemons, check if you can directly use 
`TeamPokemon` and make a single query.

2021-06-15 15:47 UTC, fjsj commented on backend/battles/services/logic_battle.py
> +    opponent_team_pokemon = TeamPokemon.objects.filter(team=opponent_team)
Check if you can make a query directly to Pokemon or TeamPokemon.
Right now you're querying teams from battle, then users from teams, then teampokemons from users, then pokemons from teampokemons.
Please try to reduce this indirection.

2021-06-15 15:47 UTC, fjsj requested changes
Please check comments

2021-06-16 15:29 UTC, fjsj commented on backend/battles/services/logic_battle.py
> +        "creator": [pokemon.pokemon for pokemon in creator_team_pokemon],
As you access each `pokemon` from `TeamPokemon`, you make new queries.
You can prevent that by doing:
```
TeamPokemon.objects.filter(
    team__trainer=battle.creator,
    team__battle=battle 
).select_related('pokemon')
```

2021-06-16 15:29 UTC, fjsj commented on backend/battles/services/logic_battle.py
> +        "creator": [pokemon.pokemon for pokemon in creator_team_pokemon],
Then keep this code as is (`pokemon.pokemon`)

2021-06-16 15:30 UTC, fjsj requested changes
Please check comments

2021-06-17 16:37 UTC, naftalima commented on backend/battles/services/logic_battle.py
> +        "creator": [pokemon.pokemon for pokemon in creator_team_pokemon],
nice!

2021-06-17 16:43 UTC, fjsj approved these changes
LGTM

2021-06-17 18:27 UTC, merged