Refactor/templates
naftalima/pokebattle pull request #16
Opened 2021-06-15 14:00 UTC by naftalima

## Objective and Motivation
- The flow wasn't good.

2021-06-15 15:07 UTC, naftalima commented
I've already deployed and tested it: everything is working.

2021-06-15 15:27 UTC, fjsj commented on backend/battles/templates/battles/battle_detail.html
> +      <td style="padding: 0 6px; width: fit-content;">
You should avoid inline styles, fix the CSS instead.

2021-06-15 15:28 UTC, fjsj requested changes
Please check comments

2021-06-16 12:51 UTC, naftalima commented on backend/battles/templates/battles/battle_detail.html
> +      <td style="padding: 0 6px; width: fit-content;">
are you talking about the style in base.html?

2021-06-16 12:53 UTC, fjsj commented on backend/battles/templates/battles/battle_detail.html
> +      <td style="padding: 0 6px; width: fit-content;">
You're using style attributes in HTML tags. Like here: `<td style="...">`
You should use CSS instead. Does that make sense?

2021-06-16 13:45 UTC, naftalima commented on backend/battles/templates/battles/battle_detail.html
> +      <td style="padding: 0 6px; width: fit-content;">
yes!!

2021-06-17 17:40 UTC, fjsj approved these changes
LGTM

2021-06-17 18:52 UTC, merged