feat: add login required mixin
naftalima/pokebattle pull request #20
Opened 2021-06-29 12:11 UTC by naftalima

## Objective and Motivation
-  Add LoginRequired mixin to all requests by non-authenticated users will be redirected to the login page

2021-06-29 12:28 UTC, fjsj commented on backend/battles/views.py
> +    login_url = "/admin/"
You can define this via Django setting, please look for it. And I think it can be the view name, instead of the URL, like `admin:login`

Also, you should consider creating your own login view, not using admin's one.

2021-06-29 12:28 UTC, fjsj requested changes
Please check comments

2021-06-29 12:41 UTC, naftalima commented on backend/battles/views.py
> +    login_url = "/admin/"
I didn't know that could be defined in Django's configuration - I'll look into it. Thank you!

 I just put it now so that the error 500 doesn't appear, but the login view is in the next task. 
 I'll have a meeting with Rob today.

2021-07-05 18:56 UTC, fjsj commented
@naftalima it's been some time since this PR has last been updated. Any news here?

2021-07-07 21:34 UTC, closed without merging