feat: user login
naftalima/pokebattle pull request #21
Opened 2021-07-07 13:20 UTC by naftalima

## Objective and Motivation
-   use Django LoginView to create a custom login page

2021-07-07 14:38 UTC, fjsj commented on backend/battles/templates/registration/login.html
> +{% extends 'battles/base.html' %}
One improvement here is to move the `base.html` code to out of `battles/`, since it's not tied to battles anymore. LMK if you have questions.

2021-07-07 14:39 UTC, fjsj commented on backend/battles/views.py
>      # TODO paginate_by = 10
Please remove this commented code.

2021-07-07 14:40 UTC, fjsj requested changes
Looking good, made a comment on an improvement.

2021-07-07 21:08 UTC, naftalima commented
# feat: user signup 
## Objective and Motivation
-   User can signup to an account

2021-07-07 21:20 UTC, naftalima commented
## Objective and Motivation
-  change import statement and model definition to improve readability and maintainability.
- The Little Book of Python Anti-Patterns :[ Importing django.db.models.fields](https://quantifiedcode.github.io/python-anti-patterns/django/all/maintainability/importing_django_model_fields.html)

2021-07-07 21:26 UTC, naftalima commented
I changed the base branch to `develop` because I'm going to close the `feat/login-required` branch

2021-07-08 13:35 UTC, fjsj approved these changes
LGTM.

2021-07-08 13:38 UTC, merged