Feat/pkn position
naftalima/pokebattle pull request #24
Opened 2021-07-12 19:51 UTC by naftalima

## Objective and Motivation
-  The trainer can choose the position of the PKN in the battle form

2021-07-12 19:54 UTC, naftalima commented
I made the request to Rebeca by accident ;(
Sorry!! enjoy your vacation!!

2021-07-12 21:06 UTC, fjsj commented on backend/battles/forms.py
> +        pokemons_data = [get_pokemon_info(pokemon_id) for pokemon_id in pokemons_id]
I don't think you need those changes in `def clean` because you're not using the pokemon position data here.
All you need is to save it in the DB, which you already are doing by using the position fields in the modelform.

2021-07-12 21:06 UTC, fjsj requested changes
Please check comments

2021-07-13 13:43 UTC, naftalima commented on backend/battles/forms.py
> +        pokemons_data = [get_pokemon_info(pokemon_id) for pokemon_id in pokemons_id]
okay!

2021-07-13 13:51 UTC, naftalima commented on backend/battles/forms.py
> +        pokemons_data = [get_pokemon_info(pokemon_id) for pokemon_id in pokemons_id]
Nice! but I use the pokemon information to check if the team is valid

2021-07-13 15:36 UTC, fjsj commented on backend/battles/forms.py
> +        pokemons_id = [str(x[1]) for x in pokemons_id]
is this working? why do you do `str(x[1])`?

2021-07-13 15:37 UTC, fjsj commented on backend/battles/services/logic_team_pokemon.py
> +        return True
I think this function is wrong. This `return True` is inside the `for`, so you're only checking the first position.

2021-07-13 15:37 UTC, fjsj requested changes
Please check comments.

2021-07-13 18:22 UTC, naftalima commented on backend/battles/forms.py
> +        pokemons_id = [str(x[1]) for x in pokemons_id]
Because the id is a string and not an integer.

2021-07-13 18:22 UTC, naftalima commented on backend/battles/services/logic_team_pokemon.py
> +        return True
Good Catch!! Thank you

2021-07-13 19:03 UTC, fjsj commented on backend/battles/forms.py
> +        pokemons_id = [str(x[1]) for x in pokemons_id]
but why not `x` only, instead of `x[1]`?

2021-07-13 19:07 UTC, naftalima commented on backend/battles/forms.py
> +        pokemons_id = [str(x[1]) for x in pokemons_id]
good catch! I forgot to remove and I've no idea how this was working.

2021-07-13 19:11 UTC, naftalima commented on backend/battles/forms.py
> +        pokemons_id = [str(x[1]) for x in pokemons_id]
done @fjsj thank you

2021-07-13 19:11 UTC, fjsj approved these changes
LGTM, thanks!

2021-07-13 19:13 UTC, merged