Feat: get all pokemons from API
naftalima/pokebattle pull request #30
Opened 2021-07-22 18:28 UTC by naftalima

## Objective and Motivation
- Using Celery Beat to download all the Pokemon at a specific day of the week.

2021-07-23 14:37 UTC, rsarai requested changes
Periodic tasks should be added in the following way: https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html#introduction. I recommend you to set the periodic tasks manually since it's the way we do it on our projects

2021-07-23 14:37 UTC, rsarai commented on backend/pokebattle/settings/base.py
> +    "django_celery_beat",
Why are you using this library?

2021-07-23 14:38 UTC, rsarai commented
> Periodic tasks should be added in the following way: https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html#introduction. I recommend you to set the periodic tasks manually since it's the way we do it on our projects

This should be made by adding the tasks on `celerybeat_schedule.py`

2021-07-28 19:56 UTC, naftalima commented
TODO:  'offset' to move to the next page
Add a 'limit' query parameter to the GET request: ?limit=60&offset=889

2021-08-02 13:15 UTC, closed without merging