FEAT: get all pokemon from POKEAPI and save
naftalima/pokebattle pull request #33
Opened 2021-08-02 17:54 UTC by naftalima

## Objective and Motivation
- Using Celery Beat to download all the Pokemon on a specific day of the week.

2021-08-03 13:14 UTC, rsarai requested changes
I think I already reviewed this code :thinking:

2021-08-03 18:51 UTC, naftalima commented
> I think I already reviewed this code

This one has a different crontab and it's not using [Database-backed Periodic Tasks](https://github.com/celery/django-celery-beat).

2021-08-03 21:25 UTC, naftalima commented
I need to hit the API again to fetch pokemon details because the first one returns only the names

2021-08-04 20:52 UTC, rsarai approved these changes

2021-08-05 12:27 UTC, merged