FEAT: autocomplete pokemons name
naftalima/pokebattle pull request #34
Opened 2021-08-02 20:35 UTC by naftalima

## Objective and Motivation
-  See available PKNs as type their names in the form (type ahead)

2021-08-03 13:08 UTC, rsarai requested changes

2021-08-03 13:08 UTC, rsarai commented on backend/templates/battles/battle-team-pokemons.html
> +          {% endfor %}
The indentation of this file is off. Also you are missing a closing tag `</option>`

2021-08-03 13:08 UTC, rsarai commented on backend/templates/battles/battle-team-pokemons.html
> +          {% endfor %}
Please fix the indentation

2021-08-03 13:08 UTC, rsarai commented on backend/templates/battles/battle-team-pokemons.html
> +          {% endfor %}
Same as above

2021-08-03 13:08 UTC, rsarai commented on backend/battles/services/api_integration.py
> +        pokemon_name = pokemon_result["name"]
Do you really need to hit the API again to fetch pokemon details?

2021-08-03 19:04 UTC, naftalima commented on backend/battles/services/api_integration.py
> +        pokemon_name = pokemon_result["name"]
now I get it... I mixed the two PRs when I merged.

2021-08-03 19:04 UTC, naftalima commented on backend/battles/services/api_integration.py
> +        pokemon_name = pokemon_result["name"]
it shouldn't be here

2021-08-03 19:05 UTC, naftalima commented on backend/battles/services/api_integration.py
> +        pokemon_name = pokemon_result["name"]
but yes I need it because the first one returns all the names and this one to save the pokemons info to save.

2021-08-03 19:06 UTC, naftalima commented on backend/battles/services/api_integration.py
> +        pokemon_name = pokemon_result["name"]
@rsarai  can we take this conversation to the other PR? here it should just be the autocomplete

2021-08-04 20:51 UTC, rsarai approved these changes

2021-08-05 12:27 UTC, merged