FEAT: RESTful endpoint - Battle
naftalima/pokebattle pull request #51
Opened 2021-09-03 18:57 UTC by naftalima

## Objective and Motivation
-  RESTful endpoint to server the React Frontend

## Serializers
* <code>UserSerializer</code>
* <code>BattleSerializer</code>
* <code>CreateBattleSerializer</code>

## Endpoints ( views) :
### BattleListView
- 
### CreateBattleView
-

## Test Cases 
### BattleListTests
| Test     | Description  | Assert     |
| :---        |    :----   |   :--- |  
| <code>test_return_200_when_accessing_endpoint </code>  | |  <code>assertResponse200 </code>   |
| <code>test_return_queryset </code>  | |  <code>assertTrue </code> ,   <code>assertEqual </code> |
| <code>test_return_empty_queryset </code>  | |  <code>assertFalse </code>   |

2021-09-10 16:41 UTC, rsarai requested changes
Looking good overall, but please remove the empty files: `backend/battles/serializers.py`, `backend/battles/endpoints.py`, and `backend/battles/drf_urls.py`

2021-09-10 16:41 UTC, rsarai commented on backend/battles/api/serializers.py
> +        fields = ("id", "creator", "opponent", "winner", "created_at")
Shouldn't the winner be defined above as well

2021-09-10 16:41 UTC, rsarai commented on backend/battles/api/serializers.py
> +    opponent = serializers.CharField(style={"base_template": "textarea.html"})
Why do you need this: `style={"base_template": "textarea.html"}`?

2021-09-10 16:41 UTC, rsarai commented on backend/battles/forms.py
> +            opponent = create_guest_opponent(opponent_email)
Nice!

2021-09-10 16:41 UTC, rsarai commented on backend/battles/api/views.py
> +class CreateBattleView(generics.CreateAPIView):
Shouldn't you send the email here: https://github.com/naftalima/pokebattle/blob/main/backend/battles/views.py#L32 ?

2021-09-10 16:41 UTC, rsarai commented on backend/battles/api/urls.py
> +    path("battle/new/", CreateBattleView.as_view(), name="battle_create"),
are the `name` attributes unique?

2021-09-13 18:53 UTC, naftalima commented on backend/battles/api/serializers.py
> +    opponent = serializers.CharField(style={"base_template": "textarea.html"})
I don't need to, but I didn't know that - I was using the django-rest-framework tutorial as a base. You can see it here: https://www.django-rest-framework.org/tutorial/1-serialization/#creating-a-serializer-class

removed

2021-09-13 18:59 UTC, naftalima commented on backend/battles/api/views.py
> +class CreateBattleView(generics.CreateAPIView):
I added sending emails, but in this PR: https://github.com/naftalima/pokebattle/pull/55

2021-09-13 18:59 UTC, naftalima commented on backend/battles/api/urls.py
> +    path("battle/new/", CreateBattleView.as_view(), name="battle_create"),
yes

2021-09-13 19:05 UTC, naftalima commented on backend/battles/api/serializers.py
> +        fields = ("id", "creator", "opponent", "winner", "created_at")
I don't quite understand. Is this a question? 
It's working like this, what should I change?

2021-09-20 12:45 UTC, rsarai approved these changes

2021-10-01 12:26 UTC, merged