Feat/team endpoints
naftalima/pokebattle pull request #52
Opened 2021-09-09 12:24 UTC by naftalima

## Objective and Motivation
-  RESTful endpoint to server the React Frontend

## Serializers
* <code>SelectTeamSerializer</code>
* <code>PokemonSerializer</code>

## Endpoints ( views) :
### SelectTeamView
-  `UpdateAPIView`

## Test Cases 
### BattleListTests
| Test     | Description  | Assert     |
| :---        |    :----   |   :--- |  
| <code>test_update_team_correct </code>  | to-do |  <code>assertResponse200 </code>   |

2021-09-10 16:47 UTC, rsarai requested changes

2021-09-10 16:47 UTC, rsarai commented on backend/battles/api/serializers.py
> +        return instance
Nice, please add a `create` method that raises a non-implemented error

2021-09-10 16:47 UTC, rsarai commented on backend/battles/api/tests/test_views.py
> +        self.assertTrue(team_pokemon)
Please assert that the pokemon data is correct, check for each pokemon

2021-09-10 16:47 UTC, rsarai commented on backend/battles/api/urls.py
> +    path("team/<int:pk>/edit/", SelectTeamView.as_view(), name="team_edit"),
Is the `name` unique?

2021-09-10 16:47 UTC, rsarai commented on backend/battles/api/views.py
> +class SelectTeamView(generics.UpdateAPIView):
The winner logic shouldn't be here as well? https://github.com/naftalima/pokebattle/blob/main/backend/battles/views.py#L53

2021-09-13 19:09 UTC, naftalima commented on backend/battles/api/urls.py
> +    path("team/<int:pk>/edit/", SelectTeamView.as_view(), name="team_edit"),
yes

2021-09-13 19:11 UTC, naftalima commented on backend/battles/api/views.py
> +class SelectTeamView(generics.UpdateAPIView):
I run the battle and send the email with the results in this PR: https://github.com/naftalima/pokebattle/pull/55

2021-09-15 17:54 UTC, naftalima commented on backend/battles/api/tests/test_views.py
> +        self.assertTrue(team_pokemon)
I'm not able to do this, because it's just returning the id which is different from what is actually in the BD.

2021-09-20 12:48 UTC, rsarai commented on backend/battles/api/serializers.py
> +        return instance
yes, please add a create method that returns this exception

2021-09-20 12:52 UTC, rsarai commented on backend/battles/api/tests/test_views.py
> +        self.assertTrue(team_pokemon)
I don't follow. You are updating the team, therefore the team data is changing, you should be able to check if what you passed on `team_pokemon_data` was correctly created on the database

2021-10-01 12:30 UTC, merged