FEAT: permissions
naftalima/pokebattle pull request #53
Opened 2021-09-09 13:39 UTC by naftalima

## Objective and Motivation
- Only authenticated users can access endpoints
- A custom permission class `IsTheTrainerOfTheTeam` for only the trainer of the team can select pokemons for that team.

2021-09-10 16:53 UTC, rsarai requested changes

2021-09-10 16:53 UTC, rsarai commented on backend/battles/api/permissions.py
> +        if str(obj.trainer) == str(request.user):
I advise you to be more specific here: `if obj.trainer.email == request.user.email:`

2021-09-10 16:53 UTC, rsarai commented on backend/battles/api/permissions.py
> +class IsTheTrainerOfTheTeam(permissions.BasePermission):
You don't need to add the `The` word

2021-09-10 16:53 UTC, rsarai commented on backend/battles/api/tests/test_views.py
> +        mock_get_pokemon.side_effect = side_effect_func
Please check if this is being called

2021-09-10 16:53 UTC, rsarai commented on backend/battles/api/tests/test_views.py
> +        self.auth_client.patch(
The permission should raise a different status_code, please check for it

2021-09-15 16:09 UTC, naftalima commented on backend/battles/api/permissions.py
> +class IsTheTrainerOfTheTeam(permissions.BasePermission):
it was really weird, thank you.

2021-09-15 16:11 UTC, naftalima commented on backend/battles/api/permissions.py
> +        if str(obj.trainer) == str(request.user):
done!

2021-09-15 16:19 UTC, naftalima commented on backend/battles/api/tests/test_views.py
> +        mock_get_pokemon.side_effect = side_effect_func
is to check if the response is 403 (forbidden) right?

2021-09-15 16:27 UTC, naftalima commented on backend/battles/api/tests/test_views.py
> +        self.auth_client.patch(
I added the check if the answer is 403

2021-09-15 16:29 UTC, naftalima commented on backend/battles/api/tests/test_views.py
> +        mock_get_pokemon.side_effect = side_effect_func
Sorry, but I didn't understand what's not being called.

2021-09-20 12:56 UTC, rsarai commented on backend/battles/api/tests/test_views.py
> +        mock_get_pokemon.side_effect = side_effect_func
If the user can't access view, this mock will never be called. You should add: `mock_get_pokemon.assert_not_called()`

2021-09-20 12:56 UTC, rsarai approved these changes

2021-09-20 12:57 UTC, rsarai commented
Please fix the mock before merging it :eyes:

2021-10-01 12:52 UTC, merged