Feat/pokebattle flow
naftalima/pokebattle pull request #9
Opened 2021-05-17 15:42 UTC by naftalima

## Objective and Motivation
- Change the flow of the Pokebattle to make it more coherent with the new models

2021-05-19 18:11 UTC, rsarai requested changes
@naftalima I made a lot of suggestions regarding names. One of the things that makes a system complex is a need for extra information in order to complete a task. In this case, one was supposed to know that a battle has trainers in order to understand that SelectTrainers is in reality creates battles. I advise you to avoid this type of cognitive load. More info on this here: https://vinta.atlassian.net/wiki/spaces/development/blog/2021/05/05/1686667278/Symptoms+of+complexity

2021-05-19 18:11 UTC, rsarai commented on backend/battles/pokemon.py
> +from urllib.parse import urljoin
Nothing here is being used right? You can add this in a different PR.

2021-05-19 18:11 UTC, rsarai commented on backend/battles/services/battle.py
> +def battle_round(creator_pkn, opponent_pkn):
Nothing here is being used right? You can add this in a different PR.

2021-05-19 18:11 UTC, rsarai commented on backend/battles/forms.py
>  class TrainersRoundForm(forms.ModelForm):
or just `BattleForm`

2021-05-21 13:15 UTC, naftalima commented on backend/battles/forms.py
> +from .models import Battle  # , Team
ok!

2021-05-21 13:28 UTC, naftalima commented on backend/battles/views.py
> +        }
No. I did it myself. should I change? and if so, what is wrong?

2021-05-21 13:31 UTC, naftalima commented on backend/battles/pokemon.py
> +from urllib.parse import urljoin
This code is **old** - I was afraid to lose it again.

2021-05-21 13:32 UTC, naftalima commented on backend/battles/services/battle.py
> +def battle_round(creator_pkn, opponent_pkn):
same here

2021-05-21 13:33 UTC, naftalima commented on backend/battles/pokemon.py
> +from urllib.parse import urljoin
but I won't do it again

2021-05-21 13:34 UTC, naftalima commented on backend/battles/forms.py
> +from .models import Battle  # , Team
this was an old code, but I will not send it again in PR

2021-05-21 14:02 UTC, naftalima commented on backend/battles/views.py
> +        ) | Battle.objects.filter(opponent__exact=self.request.user)
Cool! Good to know. I will use this Q object.

2021-05-21 14:16 UTC, naftalima commented on backend/battles/views.py
> +        ) | Battle.objects.filter(opponent__exact=self.request.user)
done

2021-05-26 13:34 UTC, rsarai requested changes

2021-05-26 13:35 UTC, rsarai commented on backend/battles/views.py
> +class BattlesView(ListView):  # pylint: disable=too-many-ancestors
This name could be improved to make the behavior more clear, like for instance `BattleListView`

2021-05-31 18:35 UTC, rsarai approved these changes

2021-06-01 12:40 UTC, merged